#!/usr/bin/env python
from websb.serverbrowser import Server, ServerBrowser, Player, Base, Scan
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from websb.config import database_uri, delay
from time import sleep
def main():
    sb = ServerBrowser()
    engine = create_engine(database_uri)
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()
    while True:
        print "Updating..."
        sb.update()
        session.add(sb.get_scan())
        session.commit()
        print "Updated!"
        sleep(delay)
if __name__ == "__main__":
    main()